### PR TITLE
Merge alembic_io in voctree_localizer

### PR DESCRIPTION
**Pull request by caymard**
We need it to perform GT tests on new localizations methods

### CODE REVIEW

**Comment by simogasp** [comment]
Can I merge? there are other changes that have to be pushed?

**Comment by caymard** [comment]
I wanted to push up the merge today yes. We need it to export and evaluate properly the localization. Especially in @lclavet cctag branch.

**Comment by simogasp** [comment]
So shall i go on and merge?

**Comment by caymard** [comment]
Yes of course !

**Comment by caymard** [comment]
Thanks

**Pull request merged**
