### PR TITLE
[WIP] cctag rig localization

### PR DESCRIPTION
**Pull request by simogasp**
Features:
* [x] new feature describer that mix sift and cctag transparently (`SIFT_CCTAG`)
* [x] voctree localization with `SIFT_CCTAG`
* [x] rig localization with CCTAG only poparteu/openMVG#13

### CODE REVIEW

**Comment by fabiencastan** [comment]
What is the status of this PR?

**Comment by simogasp** [comment]
I'm developing the rig localization with cctag on this branch for the moment is just a WIP

**Comment by fabiencastan** [comment]
So maybe we can rename the PR?

**Comment by simogasp** [comment]
i added the features that are implemented in this PR

**Pull request merged**
